version: "3.7"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: dev-game-deals
    volumes:
      - "./container-data/mongo:/data/db"
    ports:
      - "27017:27017"
  frontenddev:
    image: node:latest
    working_dir: /mnt
    volumes:
      - "./frontend:/mnt"
    command: ./scripts/dev.sh
  backenddev:
    image: node:latest
    working_dir: /mnt
    volumes:
      - "./server:/mnt"
    command: ./scripts/dev.sh
