version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: devgamedeals
      POSTGRES_PASSWORD: devgamedeals
      POSTGRES_DB: devgamedeals
    volumes:
      - "postgresdata:/var/lib/postgresql/data/"
    restart: always
  nginx:
    image: nginx:latest
    volumes:
      - "./dev-nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8000:8000"
    restart: always
  frontend:
    image: node:latest
    working_dir: /mnt
    volumes:
      - "./frontend:/mnt"
    command: ./scripts/dev.sh
    restart: always
  backend:
    image: node:latest
    working_dir: /mnt
    volumes:
      - "./server:/mnt"
    command: ./scripts/dev.sh
    restart: always
volumes:
  postgresdata: {}
