version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: devgamedeals
      POSTGRES_PASSWORD: devgamedeals
      POSTGRES_DB: devgamedeals
      PGPASSWORD: devgamedeals # For psql
    volumes:
      - "postgresdata:/var/lib/postgresql/data/"
    restart: always
  nginx:
    image: nginx:latest
    volumes:
      - "./dev-nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8000:8000"
    restart: always
  frontend:
    image: node:latest
    working_dir: /mnt/frontend
    volumes:
      - "./:/mnt"
    command: ./scripts/dev.sh
    ports:
      - "8003:8003" # Hot reload web socket
    restart: always
  backend:
    image: node:latest
    working_dir: /mnt/backend
    volumes:
      - "./:/mnt"
    environment:
      - GAME_DEALS_DB_AUTO_MIGRATE=true
    command: ./scripts/dev.sh
    restart: always
volumes:
  postgresdata: {}
