version: "3.7"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: dev-game-deals
    volumes:
      - "./container-data/mongo:/data/db"
  nginxdev:
    image: nginx:latest
    volumes:
      - "./dev-nginx.conf:/etc/nginx/nginx.conf"
      - "frontenddist:/mnt/frontenddist"
    ports:
      - "8000:8000"
  frontenddev:
    image: node:latest
    working_dir: /mnt
    volumes:
      - "./frontend:/mnt"
      - "frontenddist:/mnt/dist"
    ports:
      - "1235:1235"
    command: ./scripts/dev.sh
  backenddev:
    image: node:latest
    working_dir: /mnt
    volumes:
      - "./server:/mnt"
    command: ./scripts/dev.sh
volumes:
  frontenddist: {}
