version: "3.7"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: dev-game-deals
    volumes:
      - "./container-data/mongo:/data/db"
    ports:
      - "27017:27017"
