# Builds and deploys the master branch.

name: Continuous Deploymeny

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout branch 📥
      uses: actions/checkout@v2
      
    - name: Install dependencies 🗄️
      run: yarn install
    
    - name: Build 🛠️
      run: yarn build

    - name: Install SSH Client 📞
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        SSH: true
        BRANCH: gh-pages
        FOLDER: public
